-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 18:50:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat_project` DEFAULT CHARACTER SET utf8 ;
USE `chat_project` ;

-- -----------------------------------------------------
-- Table `chat_project`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_project`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_project`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_project`.`Chat` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`chat_id`),
  UNIQUE INDEX `chat_id_UNIQUE` (`chat_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_project`.`UserChat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_project`.`UserChat` (
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `chat_id`),
  INDEX `fk_User_has_Chat_Chat1_idx` (`chat_id` ASC) VISIBLE,
  INDEX `fk_User_has_Chat_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Chat_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat_project`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Chat_Chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `chat_project`.`Chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat_project`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat_project`.`Message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `user_id`, `chat_id`),
  UNIQUE INDEX `message_id_UNIQUE` (`message_id` ASC) VISIBLE,
  INDEX `fk_Message_UserChat1_idx` (`user_id` ASC, `chat_id` ASC) VISIBLE,
  CONSTRAINT `fk_Message_UserChat1`
    FOREIGN KEY (`user_id` , `chat_id`)
    REFERENCES `chat_project`.`UserChat` (`user_id` , `chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
